[build]
builder = "nixpacks"
buildCommand = "cd backend && ./gradlew build"

[deploy]
startCommand = "cd backend && java -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"

[env]
PORT = "8090" 