[build]
builder = "nixpacks"
buildCommand = "cd backend && ./gradlew build"

[deploy]
startCommand = "cd backend && java -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8090" 