spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/f1chatter}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # For Render's PostgreSQL connection pooling
        connection:
          provider_disables_autocommit: true

server:
  port: ${PORT:8090}

logging:
  level:
    com.f1chatter: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
