spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:dummy-client-id}
            client-secret: ${FACEBOOK_CLIENT_SECRET:dummy-client-secret}
            scope: email, public_profile

server:
  port: 8090
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.f1chatter.backend.service.JolpicaApiService: DEBUG

jolpica:
  api:
    base-url: https://api.jolpi.ca/ergast/f1
    rate-limit:
      requests-per-second: 3
      max-retries: 3
    
sportmonks:
  api:
    base-url: https://api.sportmonks.com/v3/formula-one
    key: ${SPORTMONKS_API_KEY:your-api-key-here} 